version: '3.1'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres


  backend_auth:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    container_name: backend_auth
    ports:
      - "5000:5000"
    depends_on:
      - db


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080